[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ddprimer"
version = "0.1.0"
description = "A pipeline for designing primers optimized for droplet digital PCR with cross-species support"
readme = "README.md"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
requires-python = ">=3.7"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "biopython",
    "pandas",
    "numpy",
    "tqdm",
    "primer3-py",
    "openpyxl>=3.0.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.10.0", 
    "black>=20.8b1",
]

[project.urls]
Homepage = "https://github.com/yourusername/ddPrimer"

[project.scripts]
ddprimer = "ddprimer.pipeline:main"

[tool.setuptools]
packages = ["ddprimer"]